const tasks = [
    {
      name: "finish task routes",
      due_date: 05 / 10 / 2023,
      description: "finish the routes associated with the tasks model",
      status: 1,
      ProjectId: 1,
    },
    {
      name: "finish user routes",
      due_date: 05 / 11 / 2023,
      description: "finish the routes associated with the users model",
      status: 2,
      ProjectId: 1,
    },
    {
      name: "finish project routes",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 4,
      ProjectId: 1,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 3,
      ProjectId: 5,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 3,
      ProjectId: 6,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 3,
      ProjectId: 7,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 2,
      ProjectId: 8,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 2,
      ProjectId: 9,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 2,
      ProjectId: 10,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 1,
      ProjectId: 11,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 1,
      ProjectId: 12,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 1,
      ProjectId: 13,
    },
    {
      name: "Show Project",
      due_date: 05 / 13 / 2023,
      description: "finish the routes associated with the projects model",
      status: 4,
      ProjectId: 14,
    },
  ];

module.exports = tasks